/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testmex;
import java.sql.*;
/**
 *
 * @author marman
 */
public class chat extends javax.swing.JFrame {
    public String destinatario;
    public String mittente;
    /**
     * Creates new form chat
     */
    public chat(String mittente, String destinatario) {
        this.destinatario = destinatario;
        this.mittente = mittente;
        initComponents();
    }
    
    public String[] chat(){
    String[] messaggi = new String[20];
    
    try{  
            // create the mysql insert preparedstatement
            String query = "SELECT testo,mittente,destinatario FROM messaggi WHERE destinatario =? AND mittente =?" +
                           "UNION\n" +
                           "SELECT testo,mittente,destinatario FROM messaggi WHERE destinatario =? AND mittente =?";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query); 
            ps.setString(1,destinatario);
            ps.setString(2,mittente);
            ps.setString(3,mittente);
            ps.setString(4,destinatario);
            ResultSet rs=ps.executeQuery();
            int i = 0;
            while(rs.next()){
            String testomsg = rs.getString("testo");
            String mit = rs.getString("mittente");
            
            messaggi[i] = mit+": "+testomsg;
            System.out.println(messaggi[i]);
            i++;
            
            }
            }
        catch(Exception e){ System.out.println(e);} 
    
    return messaggi;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messaggio = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("invia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        messaggio.setColumns(20);
        messaggio.setRows(5);
        jScrollPane2.setViewportView(messaggio);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = chat();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{  
            // create the mysql insert preparedstatement
            String query = "INSERT INTO messaggi (mittente,destinatario,testo)" + " VALUES (?,?,?)";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query);          

            ps.setString (1, mittente);
            ps.setString (2, destinatario);
            ps.setString  (3, messaggio.getText());
          
            // execute the preparedstatement
            ps.execute();
            
            }
        catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messaggio;
    // End of variables declaration//GEN-END:variables
}
