/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testmex;
import java.sql.*;
import javax.swing.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author marman
 */
public class rubrica extends javax.swing.JFrame {
    public String nomeUtente;
    public String destinatario;
    /**
     * Creates new form rubrica
     */
    public rubrica(String uname) {
        nomeUtente = uname;
        initComponents();
        
        
        }
    
    
    
    public String[] lstUtn(){
    String[] utenti = new String[20];
    
    try{  
            // create the mysql insert preparedstatement
            String query = "SELECT userName FROM utenti";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query);          
            ResultSet rs=ps.executeQuery();
            int i = 0;
            while(rs.next()){
            String nome = rs.getString("userName");
            if(!nome.equals(nomeUtente)) {utenti[i] = nome;}
            i++;
            
            }
            }
        catch(Exception e){ System.out.println(e);} 
    
    return utenti;
    
    }
    
    public String[] lstMsg(){
    String[] messaggi = new String[20];
    
    try{  
            // create the mysql insert preparedstatement
            String query = "SELECT testo,mittente FROM messaggi WHERE destinatario =?";
            PreparedStatement ps = MyConnection.getConnection().prepareStatement(query); 
            ps.setString(1,nomeUtente);
            ResultSet rs=ps.executeQuery();
            int i = 0;
            while(rs.next()){
            String nome = rs.getString("testo");
            String mit = rs.getString("mittente");
            messaggi[i] = mit+": "+nome;
            i++;
            
            }
            }
        catch(Exception e){ System.out.println(e);} 
    
    return messaggi;
    
    }
        
              
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = lstUtn();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("visualizza mesaggi ricevuti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = lstMsg();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jButton3.setText("refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(78, 78, 78)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
            // TODO add your handling code here:
            
            if (evt.getClickCount() == 2) {
            int index = jList1.locationToIndex(evt.getPoint());
            if (index >= 0) {
            Object o = jList1.getModel().getElementAt(index);
            destinatario = o.toString();
            chat c = new chat(nomeUtente,destinatario);
            c.setTitle("chat with"+destinatario);
            c.setVisible(true);
            
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = lstMsg();
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
        });
        
        JScrollPane jScrollPane3 = new JScrollPane();
        jScrollPane3.setViewportView(jList2);
        
        
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] msg = lstMsg();
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = msg;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList2.updateUI();
        
        String[] utn = lstUtn();
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = utn;
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }});
        jList1.updateUI();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:

        
        

    }//GEN-LAST:event_formMouseMoved

                                       

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
